name: Ubuntu

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build using CMake
        run: mkdir build && cd build && cmake .. && make

      - name: Run tests 
        run: ./build/tests/chaining_hashmap && ./build/tests/open_addressing_hashmap
